name: "sample"
on: [push]
jobs:
  job-1:
    runs-on: "ubuntu-latest"
    steps:
      - name: "stage-1"
        run: echo "this is stage-1"

      - name: "step-1"
        run: echo "this is stage-2"    