name: "sample"
on: [push]  ## on which actions the pipeline should run
jobs:
  job-1:  ## pipeline/job name
    runs-on: "ubuntu-latest"
    steps:
      - name: "stage-1"
        run: echo "this is stage-1"
      - name: "step-1"
        run: echo "this is stage-2"    