name: "terraform"
on: [push]
jobs:
  job1:
    runs-on: "ubuntu-latest"
    steps:
    - name: "checkout the code"
      uses: actions/checkout@v5

    - name: "need terraform to run terraform commands"
      uses: hashicorp/setup-terraform@v2

    - name: "intialize"
      run: terraform init

    - name: "Aws authenticate"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRETS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: us-east-1
    - name: "plan"
      run: terraform plan

    - name: "terraform apply"
      run: terraform apply -auto-approve        