# "uses" is used to when we want to use an action and it was already available as a plugin. 

name: "uses"
on: [push]
jobs:
  job1:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - name: step-2
        run: echo "the above step will checkout the repo"
      - name: step-3
        run: ls -la 
